modLoader="javafml"
loaderVersion="[43,)"
license="GNU_GPL.3"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/"
[[mods]]
modId="todevillagers"
version="1.19.2-0.1.3"
displayName="Tode Villagers"
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
displayURL="https://github.com/toadie-odie/TodeVillagers"
logoFile="logo.png"
credits="Special thanks to my sons, and my Patreon supporters: Marshal Nash and Trevor Brannigan, for supporting my blog and my various project!"
authors="Warren Tode (ToadieOdie)"
description="This mod adds a variety of villagers with their trades to the game."

[[dependencies.todevillagers]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.todevillagers]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
